package FaultToleranceDPSS;


/**
* FaultToleranceDPSS/DPSS_FTHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FaultToleranceDPSS.idl
* Sunday, August 2, 2020 5:22:25 AM EDT
*/

abstract public class DPSS_FTHelper
{
  private static String  _id = "IDL:FaultToleranceDPSS/DPSS_FT:1.0";

  public static void insert (org.omg.CORBA.Any a, FaultToleranceDPSS.DPSS_FT that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FaultToleranceDPSS.DPSS_FT extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FaultToleranceDPSS.DPSS_FTHelper.id (), "DPSS_FT");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FaultToleranceDPSS.DPSS_FT read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DPSS_FTStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FaultToleranceDPSS.DPSS_FT value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FaultToleranceDPSS.DPSS_FT narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FaultToleranceDPSS.DPSS_FT)
      return (FaultToleranceDPSS.DPSS_FT)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FaultToleranceDPSS._DPSS_FTStub stub = new FaultToleranceDPSS._DPSS_FTStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FaultToleranceDPSS.DPSS_FT unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FaultToleranceDPSS.DPSS_FT)
      return (FaultToleranceDPSS.DPSS_FT)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FaultToleranceDPSS._DPSS_FTStub stub = new FaultToleranceDPSS._DPSS_FTStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
