package FaultToleranceDPSS;


/**
* FaultToleranceDPSS/DPSS_FT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FaultToleranceDPSS.idl
* Sunday, August 2, 2020 5:22:25 AM EDT
*/

public interface DPSS_FT extends DPSS_FTOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DPSS_FT
