package FaultToleranceDPSS;


/**
* FaultToleranceDPSS/DPSS_FTOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FaultToleranceDPSS.idl
* Sunday, August 2, 2020 5:22:25 AM EDT
*/

public interface DPSS_FTOperations 
{
  boolean logIn (String userName, String Password, String ipAddress);
  boolean createPlayerAccount (String firstName, String lastName, int Age, String userName, String Password, String IPAddress);
  boolean logOut (String userName);
  String[] getPlayerUpdate (String adminId);
  boolean suspendAccount (String adminId, String adminPword, String adminIp, String suspendAccount);
  boolean transferAccount (String userName, String Password, String oldIp, String newIp);

  //		string logIn(in string userName);
  void shutdown ();
} // interface DPSS_FTOperations
