package FaultToleranceDPSS;


/**
* FaultToleranceDPSS/ResultListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FaultToleranceDPSS.idl
* Sunday, August 2, 2020 5:22:25 AM EDT
*/

public final class ResultListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ResultListHolder ()
  {
  }

  public ResultListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FaultToleranceDPSS.ResultListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FaultToleranceDPSS.ResultListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FaultToleranceDPSS.ResultListHelper.type ();
  }

}
